// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: nostresp

#ifndef _NOSTRESP_UI_H
#define _NOSTRESP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
void ui_event_SplashScreen(lv_event_t * e);
extern lv_obj_t * ui_SplashScreen;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label9;
// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_barhashrate;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_btndelete;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_lblhashrate;
extern lv_obj_t * ui_lblshares16;
extern lv_obj_t * ui_lbltemplates;
extern lv_obj_t * ui_lblvalid;
extern lv_obj_t * ui_lblshares32;
extern lv_obj_t * ui_lblclock;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_783383759);    // assets\han-splash.png
LV_IMG_DECLARE(ui_img_sky_png);    // assets\sky.png
LV_IMG_DECLARE(ui_img_93039294);    // assets\bitcoin-btc-logo-100.png
LV_IMG_DECLARE(ui_img_metal2_png);    // assets\metal2.png

LV_FONT_DECLARE(ui_font_calculator128);
LV_FONT_DECLARE(ui_font_calculator16);
LV_FONT_DECLARE(ui_font_calculator24);
LV_FONT_DECLARE(ui_font_calculator32);
LV_FONT_DECLARE(ui_font_calculator48);
LV_FONT_DECLARE(ui_font_star24);
LV_FONT_DECLARE(ui_font_star32);
LV_FONT_DECLARE(ui_font_start16);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
