// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: nostresp

#include "../ui.h"

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_HomeScreen, &ui_img_sky_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -179);
    lv_obj_set_y(ui_Button1, 123);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, -62);
    lv_obj_set_y(ui_Button4, 124);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_Image1, &ui_img_93039294);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image1, 189);
    lv_obj_set_y(ui_Image1, -110);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_barhashrate = lv_bar_create(ui_HomeScreen);
    lv_bar_set_range(ui_barhashrate, 0, 1000);
    lv_bar_set_value(ui_barhashrate, 800, LV_ANIM_OFF);
    lv_obj_set_width(ui_barhashrate, 363);
    lv_obj_set_height(ui_barhashrate, 17);
    lv_obj_set_x(ui_barhashrate, -52);
    lv_obj_set_y(ui_barhashrate, -74);
    lv_obj_set_align(ui_barhashrate, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_barhashrate, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barhashrate, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_time(ui_barhashrate, 500, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_barhashrate, lv_color_hex(0xFAFF20), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barhashrate, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 72);
    lv_obj_set_y(ui_Label6, -46);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "16bits shares");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x2EFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_start16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -144);
    lv_obj_set_y(ui_Label4, -122);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Hashrate");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_star32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -171);
    lv_obj_set_y(ui_Label7, -47);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "valid blocks");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_start16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btndelete = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_btndelete, 100);
    lv_obj_set_height(ui_btndelete, 50);
    lv_obj_set_x(ui_btndelete, 183);
    lv_obj_set_y(ui_btndelete, 127);
    lv_obj_set_align(ui_btndelete, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btndelete, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btndelete, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btndelete, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btndelete, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -154);
    lv_obj_set_y(ui_Label8, -14);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "block templates");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_start16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 75);
    lv_obj_set_y(ui_Label10, -13);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "32bits shares");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x2EFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_start16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblhashrate = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lblhashrate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblhashrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblhashrate, 46);
    lv_obj_set_y(ui_lblhashrate, -122);
    lv_obj_set_align(ui_lblhashrate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblhashrate, "00000 h/s");
    lv_obj_set_style_text_color(ui_lblhashrate, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblhashrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblhashrate, &ui_font_calculator48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblshares16 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lblshares16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblshares16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblshares16, 173);
    lv_obj_set_y(ui_lblshares16, -47);
    lv_obj_set_align(ui_lblshares16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblshares16, "0000");
    lv_obj_set_style_text_color(ui_lblshares16, lv_color_hex(0x2EFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblshares16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblshares16, &ui_font_calculator32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbltemplates = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lbltemplates, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbltemplates, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbltemplates, 174);
    lv_obj_set_y(ui_lbltemplates, -15);
    lv_obj_set_align(ui_lbltemplates, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lbltemplates, "0000");
    lv_obj_set_style_text_color(ui_lbltemplates, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbltemplates, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbltemplates, &ui_font_calculator32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblvalid = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lblvalid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblvalid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblvalid, -72);
    lv_obj_set_y(ui_lblvalid, -49);
    lv_obj_set_align(ui_lblvalid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblvalid, "0000");
    lv_obj_set_style_text_color(ui_lblvalid, lv_color_hex(0xFF9400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblvalid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblvalid, &ui_font_calculator32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblshares32 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lblshares32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblshares32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblshares32, 171);
    lv_obj_set_y(ui_lblshares32, -15);
    lv_obj_set_align(ui_lblshares32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblshares32, "0000");
    lv_obj_set_style_text_color(ui_lblshares32, lv_color_hex(0x2EFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblshares32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblshares32, &ui_font_calculator32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblclock = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_lblclock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblclock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblclock, 119);
    lv_obj_set_y(ui_lblclock, 62);
    lv_obj_set_align(ui_lblclock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblclock, "23h 59m 59s");
    lv_obj_set_style_text_color(ui_lblclock, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblclock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblclock, &ui_font_calculator48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -33);
    lv_obj_set_y(ui_Label2, 69);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "uptime");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_start16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
